name: cd

on:
  workflow_dispatch:
  push:
    tags: 
      - "*.*.*"

permissions:
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 0 
      -
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      -
        run: npm install
      -
        run: npm run build
      - 
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
